### ISSUE TITLE
Add new functionality from `aquamonitor-python`

### ISSUE THREAD

**Issue by JamesSample** [NIVANorge/aquamonitR#9]
In Aquamonitor-Python, Roar has extended the `Query` class by improving the `map` method and adding the `list` and `pages` methods. I've also improved the performance of `get_project_chemistry` by querying results from the server in parallel. See the discussion [here ](https://github.com/NIVANorge/Aquamonitor-Python/pull/7) for details.

These new features need translating to `aquamonitR`. 

@DagHjermann Any suggestions for the simplest/cleanest way to query results from the server in parallel in R, please? It's basically a `for` loop that can be run "embarrassingly parallel", so nothing sophisticated. For Aquamonitor-Python I used [joblib](https://joblib.readthedocs.io/en/latest/parallel.html), but have never needed to do anything similar in R. Looks fairly straightforward using `foreach` and `doParallel`, but happy to hear alternative suggestions if you have them. Thanks!

**Comment by DagHjermann** [comment]
@JamesSample Yes, `foreach` and `doParallel` are the 'classic' packages for parallel computation and the only ones I've tested. As you say they are pretty straightforward and may be a good approach in this setting. There are alternatives though, see the [official Task View](https://cran.r-project.org/view=HighPerformanceComputing) for an overview. I've seen the [future](https://cran.r-project.org/package=future) and [doFuture](https://cran.r-project.org/package=doFuture) packages mentioned often as a more elegant/modern approach. RStudio has a [20 minute talk](https://www.rstudio.com/resources/rstudioconf-2020/parallel-computing-with-r-using-foreach-future-and-other-packages/) comparing these approaches, it might be worth watching.

**Comment by knl88** [comment]
Guess this is a bit old, but just open again if we want to keep it.
